name: packit
description: Tour Checklist Project
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  auto_mappr_annotation: ^2.1.0
  dio: ^5.4.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flash: ^3.1.0
  flutter:
    sdk: flutter
  flutter_carousel_slider: ^1.1.0
  flutter_debouncer: ^2.0.0
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.1.0
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter
  flutter_naver_login: ^1.8.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  image_picker: ^1.0.7
  intl: ^0.18.1
  json_annotation: ^4.8.1
  kakao_flutter_sdk: ^1.8.0
  kakao_flutter_sdk_share: ^1.8.0
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  retrofit: ^4.0.3
  sign_in_with_apple: ^5.0.0
  table_calendar: ^3.0.9

dev_dependencies:
  auto_mappr: ^2.2.0
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/icons/home/
    - assets/icons/notification/
    - assets/icons/onboarding/
    - assets/icons/profile/
    - assets/icons/tour/
    - assets/images/

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/font/SUIT-Thin.ttf
          weight: 100
        - asset: assets/font/SUIT-ExtraLight.ttf
          weight: 200
        - asset: assets/font/SUIT-Light.ttf
          weight: 300
        - asset: assets/font/SUIT-Regular.ttf
          weight: 400
        - asset: assets/font/SUIT-Medium.ttf
          weight: 500
        - asset: assets/font/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/font/SUIT-Bold.ttf
          weight: 700
        - asset: assets/font/SUIT-ExtraBold.ttf
          weight: 800
        - asset: assets/font/SUIT-Heavy.ttf
          weight: 900
