name: packit
description: Tour Checklist Project
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  animated_flip_counter: ^0.2.6
  flutter:
    sdk: flutter
  flutter_carousel_slider: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  get: ^4.6.6
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/onboarding/
    - assets/icons/tour/
    - assets/images/

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/font/SUIT-Thin.ttf
          weight: 100
        - asset: assets/font/SUIT-ExtraLight.ttf
          weight: 200
        - asset: assets/font/SUIT-Light.ttf
          weight: 300
        - asset: assets/font/SUIT-Regular.ttf
          weight: 400
        - asset: assets/font/SUIT-Medium.ttf
          weight: 500
        - asset: assets/font/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/font/SUIT-Bold.ttf
          weight: 700
        - asset: assets/font/SUIT-ExtraBold.ttf
          weight: 800
        - asset: assets/font/SUIT-Heavy.ttf
          weight: 900
